### ISSUE TITLE
Feature: Add conference schedule integration

### ISSUE THREAD

**Issue by neufeldtech** [WpgTech/gilfoyle#10]
Might have features like:
- @hubot who is speaking next? - shows which talks are up next
- @hubot who is speaking now? - shows which talks are currently happening
- @hubot schedule - shows the schedule for the conference

**Comment by neufeldtech** [comment]
You can find the schedule here: http://www.prdcdeliver.com/schedule

**Comment by dj21d** [comment]
I can implement this within the next couple days

**Comment by neufeldtech** [comment]
Thanks for implementing this @dj21d!
